site_name: FlashBase Docs
site_author: FlashBase Team
site_description: FlashBase is a DRAM / SSD optimized real-time in-memory DBMS.
site_url: https://mnms.github.io/docs
copyright: All right reserved, FlashBase Team.
google_analytics: ['UA-152587413-1', 'mnms.github.io/docs']

repo_name: source repository
repo_url: https://github.com/mnms/docs

nav:
  - Introduction: index.md
  - Get Started:
    - Automated Installation (recommanded): get-started-with-aws.md
    - Manual Installation: get-started-with-scratch.md
    - Try out with Zeppelin: try-with-zeppelin.md 
  - FBCTL:
    - Install and Upgrade: run-and-deploy-fbctl.md
    - Commands: command-line-interface.md
  - Data Ingestion and Querying: data-ingestion-and-querying.md
  - Support:
    - FAQ: FAQ.md
    - EULA: eula.md

plugins:
  - search
markdown_extensions:
  - meta
  - toc:
      permalink: true
      baselevel: 1
  - admonition
  - footnotes

theme:
  name: readthedocs
  highlightjs: true

extra:
  version: 0.1
