site_name: FlashBase Docs
site_author: FlashBase Team
site_description: FlashBase is a DRAM / SSD optimized real-time in-memory DBMS.
site_url: https://mnms.github.io/docs
copyright: All right reserved, FlashBase Team.

repo_name: source repository
repo_url: https://github.com/mnms/docs

nav:
  - Introduction: index.md
  - Get Started:
    - 1. Automated Installation (recommanded): get-started1.md 
    - 2. Manual Installation: get-started2.md
  - Commands: command-line-interface.md
  - Data Ingestion and Querying: data-ingestion-and-querying.md

plugins:
  - search
markdown_extensions:
  - meta
  - toc:
      permalink: true
      baselevel: 1
  - admonition
  - footnotes

theme:
  name: readthedocs
  highlightjs: true

extra:
  version: 0.1
